### ISSUE TITLE
Cannot read property 'value' of null

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#101]
![screen shot 2018-02-27 at 09 33 09](https://user-images.githubusercontent.com/806/36718220-4a2edb96-1ba1-11e8-88c9-a7e3d6d918c1.png)

![screen shot 2018-02-27 at 09 34 04](https://user-images.githubusercontent.com/806/36718248-61f26978-1ba1-11e8-8586-ad6ed728a32b.png)

The most simple way to reproduce it is to create a filter on `address.ip` and press space. But it's also happening in more realistic scenarios.

**Comment by jduthon** [comment]
Couldn't reproduce after my recent fixes, might or might not be fixed, but at least I cannot reproduce with the simple procedure.

**Comment by znarf** [comment]
Ok, will check.
