### ISSUE TITLE
Wrong icon

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#148]
![screen shot 2018-03-14 at 22 04 35](https://user-images.githubusercontent.com/806/37430954-14a50560-27d4-11e8-8a0e-12c04f974c9e.png)

**Comment by jduthon** [comment]
Ok so the problem with this one is our way of deciding which icon to put, it goes as following : 
1. If robot.icon => put robot.icon
2. If user-agent && !reputation.status = bad => put user-agent icon
3. If user-agent && reputation.status = bad | suspicious => suspicious icon
4. If robot => robot[reputation.status].icon
5. Unknown icon[reputation.status]

So I believe we would need to change the user-agent rule to not do it if we are dealing with a robot?
