### ISSUE TITLE
No icon/label for humans in detailed view

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#56]
![screen shot 2018-02-01 at 09 33 22](https://user-images.githubusercontent.com/806/35668786-14b23148-0733-11e8-8cf4-641ff39f9e32.png)

**Comment by jduthon** [comment]
So this one seems innocent but is actually harder than it seems.
The problem we have right now is that for Robots we are relying on the `robot.id` to get the data from the server.
In case of a human we have the `identity`, but it does not exist on the session on the agent.
So I propose we create a identity store on the frontend to keep them and to be able to retrieve them after route change?
