### ISSUE TITLE
"Feature not supported" with Elasticsearch activated

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#61]
![screen shot 2018-02-08 at 13 37 01](https://user-images.githubusercontent.com/806/35973315-40c231b4-0cd5-11e8-8746-d5092b8116a5.png)

In the same screen, the feature is actually working.

**Comment by jduthon** [comment]
I imagine you were testing with the UI decoupled from the agent.
In this case the configuration is coming from `app_config.js`, so you need to change it there :) 
It's a bit shitty, but if we are not going for something like this it means the backend should send out the configuration over an endpoint, which complicates ours configuration quite a lot for this kind of small dev details.

**Comment by znarf** [comment]
@jduthon No, I'm testing within the agent, with `npm link ../access-watch-ui`.

**Comment by jduthon** [comment]
Hm yup, we need to merge one more branch on the back-end side, creating PR and fixing conflicts

**Comment by jduthon** [comment]
https://github.com/access-watch/access-watch/pull/160 ready here
