### ISSUE TITLE
Exception in Request details

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#63]
Cannot read property find of 'undefined'.

![screen shot 2018-02-08 at 14 19 06](https://user-images.githubusercontent.com/806/35974899-1a409fd4-0cdb-11e8-961a-85948639c9c2.png)

![screen shot 2018-02-08 at 21 19 38](https://user-images.githubusercontent.com/806/35996107-d61a27ae-0d15-11e8-95b7-15a5070d2f61.png)

**Comment by jduthon** [comment]
Do you have any precision how you got this one?
I cannot reproduce right now.
Maybe it could have been fixed by #64 even though I doubt it.
I imagine it's a particular case but cannot get it.

**Comment by znarf** [comment]
I'll check again. Was easy to reproduce but not on 100% of the requests.

**Comment by jduthon** [comment]
Ok.
I checked a variety of addresses (Ok/Suspicious/Human) on both ES and memory logs and couldn't get it. But I didn't have very different logs, like all those logs had at least 10-20 logs in the details page, so maybe it needs one which have 0.

**Comment by znarf** [comment]
Not reproducing so far.
