### ISSUE TITLE
WebSocket exception

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#66]
![screen shot 2018-02-08 at 18 59 51](https://user-images.githubusercontent.com/806/35989747-483c602c-0d02-11e8-9ae3-8f13c55f92a4.png)

![screen shot 2018-02-08 at 19 00 33](https://user-images.githubusercontent.com/806/35989769-5dd787cc-0d02-11e8-9ebc-6c7a27f50786.png)

**Comment by jduthon** [comment]
When/How did it happen?

**Comment by znarf** [comment]
Might happen when the connection is terminated by the server, can we reconnect?

Without that, the user needs to hard refresh to recover.
