### ISSUE TITLE
Last X days in Addresses / Robots

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#82]
The label is misleading because the default is to present the activity from the last 24 hours.

![screen shot 2018-02-20 at 10 38 14](https://user-images.githubusercontent.com/806/36416735-354fa4ca-162a-11e8-95ea-067b03bb5036.png)

**Comment by znarf** [comment]
![screen shot 2018-02-22 at 15 35 28](https://user-images.githubusercontent.com/806/36546234-327c035c-17eb-11e8-9d04-fa5ddc043731.png)

![screen shot 2018-02-22 at 15 35 06](https://user-images.githubusercontent.com/806/36546235-329e3738-17eb-11e8-9a50-60c56b47d09b.png)

Not clear why it's 6h in that case.

**Comment by jduthon** [comment]
Because the slider doesn't affect the session?
If we want to change this though I would be up for opening another ticket. (and then I believe we also want to put the time from auto, only with a `Math.max(timeAuto, sessionRetention)`)

**Comment by znarf** [comment]
@jduthon You're right, I was confused.
