### ISSUE TITLE
Missing addresses when picking a timerange

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#83]
With Elasticsearch backend, there is too obviously too few addresses returned when picking a timerange.

![screen shot 2018-02-20 at 10 39 29](https://user-images.githubusercontent.com/806/36416788-65de0dd4-162a-11e8-928b-c3de19d9f22d.png)

**Comment by jduthon** [comment]
Which branch is this suppose to happen on?
I cannot reproduce on dev

**Comment by znarf** [comment]
Sorry, I'll try to reproduce.
