### ISSUE TITLE
Build error with Uglify

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#88]
Run ` npm run build`

Get:

```
ERROR in main.js from UglifyJs
Unexpected token: punc (,) [main.js:4696,10]
```

**Comment by jduthon** [comment]
Problems come with symlinking in local (cf. : https://www.google.de/search?q=webpack+not+working+with+npm+lik&oq=webpack+not+working+with+npm+lik&aqs=chrome..69i57j0j35i39j0l3.8270j0j1&sourceid=chrome&ie=UTF-8)

So basically when ready to publish it's anyway better to unlink anything.
For local build you can apparently get around it by changing the way webpack handles symlink : https://webpack.js.org/configuration/resolve/#resolve-symlinks
