### ISSUE TITLE
Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch-ui#94]
![screen shot 2018-02-22 at 17 06 25](https://user-images.githubusercontent.com/806/36549345-d94b97f4-17f2-11e8-9cc0-86ef1ceaa246.png)

![screen shot 2018-02-22 at 17 06 52](https://user-images.githubusercontent.com/806/36549344-d92a78da-17f2-11e8-92a7-9c3d8e7a1570.png)

Happened when clicking on a single robot from a [Robots with past timerange] screen, Elasticsearch backend.

**Comment by znarf** [comment]
Still reproducible.

**Comment by jduthon** [comment]
? 
Wrong issue no?

**Comment by znarf** [comment]
Not, just checked if I could reproduce it and it's still valid.

**Comment by jduthon** [comment]
Backend issue : https://github.com/access-watch/access-watch/issues/184
